name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Debug secrets
        run: |
          echo "VPS_HOST=${{ secrets.VPS_HOST }}"
          echo "VPS_USER=${{ secrets.VPS_USER }}"
          echo "SSH Key length: $(echo "${{ secrets.VPS_SSH_KEY }}" | wc -c)"

      - name: Deploy to VPS via SSH
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: 22
          script: |
            echo "✅ Connected to VPS: $(hostname)"
            cd /home/ubuntu/loza/TaskMasterPro
            git reset --hard
            git pull origin main
            source venv/bin/activate
            pip install -r requirements.txt
            sudo systemctl restart gunicorn
