name: Deploy to VPS

on:
  push:
    branches:
      - main   # Run deployment only when pushing to main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to VPS via SSH
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: 22
          script: |
            cd /home/ubuntu/loza/TaskMasterPro
            git reset --hard
            git pull origin main
            source venv/bin/activate
            pip install -r requirements.txt
            sudo systemctl restart gunicorn
